# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='duration',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='remind_before',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
