# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20160118_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='taskid',
        ),
        migrations.AddField(
            model_name='tasks',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
