# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20160114_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='id',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='userid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
